OPERATORS = "/*%^"
OPERATORS_PRIORITY = {"/": 2, "*": 2, "%": 2, "^": 3, "+": 1, "-": 1}
SIGN = "+-"
COMMA = "."
OPEN_PARENTHESES = "("
CLOSING_PARENTHESES = ")"
MATRICE_OPEN_PARENTHESES = "["
MATRICE_CLOSING_PARENTHESES = "]"
MATRICE_LINE_SEPARATOR = ","
MATRICE_COLUMN_SEPARATOR = ";"

VARIABLES_FILE_NAME: str = "variables.ser"
