EQUALS_SIGN = "="
DIVISION_SIGN = "/"
MODULO_SIGN = "%"
QUESTIONS_SIGN = "?"
ADDITION_SIGN = "+"
SUBSTRACTION_SIGN = "-"
EXPONENT_SIGN = "^"
MULTIPLICATION_SIGN = "*"

DIVIDING_OPERATORS = DIVISION_SIGN + MODULO_SIGN
OPERATORS = EXPONENT_SIGN + MULTIPLICATION_SIGN + DIVIDING_OPERATORS
SIGN = ADDITION_SIGN + SUBSTRACTION_SIGN

OPERATORS_PRIORITY = {
    DIVISION_SIGN: 2,
    MULTIPLICATION_SIGN: 2,
    MODULO_SIGN: 2,
    EXPONENT_SIGN: 3,
    ADDITION_SIGN: 1,
    SUBSTRACTION_SIGN: 1,
}

COMMA = "."

OPEN_PARENTHESES = "("
CLOSING_PARENTHESES = ")"

MATRICE_OPEN_PARENTHESES = "["
MATRICE_CLOSING_PARENTHESES = "]"
MATRICE_LINE_SEPARATOR = ","
MATRICE_COLUMN_SEPARATOR = ";"

ASSIGNED_FILE_NAME: str = "variables.ser"
